"use client";

import { Award, BookOpen, Check, ClipboardCheck, FileQuestion, HelpCircle, Lightbulb } from "lucide-react";

import { Badge, Card } from "@/components/ui";
import type { GeneratedCourse } from "@/types/product";

export function CoursePreviewCanvas({ course }: { course: GeneratedCourse }) {
  const lessonCount = course.modules.reduce((count, module) => count + module.lessons.length, 0);
  return (
    <article className="overflow-hidden rounded-xl border border-border-default bg-surface-default shadow-sm" aria-label="Learner course preview">
      <header className="bg-blue-900 px-5 py-10 text-white sm:px-10 sm:py-14">
        <div className="mx-auto max-w-4xl"><div className="flex flex-wrap gap-2"><Badge variant="accent">{course.level}</Badge><Badge className="bg-white/10 text-white">{course.modules.length} modules · {lessonCount} lessons</Badge></div><h1 className="mt-5 text-3xl font-semibold tracking-tight sm:text-4xl">{course.title}</h1><p className="mt-4 max-w-3xl text-lg leading-8 text-blue-100">{course.description}</p></div>
      </header>
      <div className="mx-auto max-w-5xl p-5 sm:p-8 lg:p-10">
        <section className="grid gap-5 lg:grid-cols-[minmax(0,1fr)_18rem]"><div><h2 className="type-h3">What you’ll learn</h2><ul className="mt-4 grid gap-3">{course.learningObjectives.map((objective) => <li key={objective} className="flex gap-3 text-text-secondary"><span className="mt-0.5 flex size-6 shrink-0 items-center justify-center rounded-full bg-status-success-subtle text-status-success"><Check className="size-3.5" aria-hidden="true" /></span>{objective}</li>)}</ul></div><Card className="h-fit bg-neutral-25 p-5"><p className="type-caption font-semibold tracking-wide text-text-tertiary uppercase">Designed for</p><p className="type-body-small mt-2 text-text-secondary">{course.targetLearner}</p></Card></section>

        <section className="mt-10" aria-labelledby="preview-curriculum"><h2 id="preview-curriculum" className="type-h3">Course content</h2><p className="type-body-small mt-2 text-text-secondary">Expand modules and lessons to inspect the learner-facing structure.</p><div className="mt-5 grid gap-4">{course.modules.map((module, moduleIndex) => <details key={module.id} className="group rounded-lg border border-border-default bg-surface-default" open={moduleIndex === 0}><summary className="flex min-h-14 cursor-pointer list-none items-center gap-4 rounded-lg p-4 focus-visible:outline-none focus-visible:ring-3 focus-visible:ring-border-focus/30 sm:p-5"><span className="flex size-10 shrink-0 items-center justify-center rounded-md bg-blue-100 text-blue-800"><BookOpen className="size-5" aria-hidden="true" /></span><span className="min-w-0 flex-1"><span className="type-caption block text-text-tertiary">Module {moduleIndex + 1}</span><span className="block font-semibold">{module.title}</span></span><Badge variant="neutral">{module.lessons.length} lessons</Badge></summary><div className="border-t border-border-default bg-neutral-25 p-3 sm:p-5"><p className="type-body-small mb-4 text-text-secondary">{module.description}</p><div className="grid gap-3">{module.lessons.map((lesson, lessonIndex) => <details key={lesson.id} className="rounded-md border border-border-default bg-surface-default"><summary className="flex min-h-12 cursor-pointer list-none items-center gap-3 rounded-md p-3 focus-visible:outline-none focus-visible:ring-3 focus-visible:ring-border-focus/30"><span className="type-caption text-text-tertiary">{moduleIndex + 1}.{lessonIndex + 1}</span><span className="flex-1 font-medium">{lesson.title}</span>{lesson.exercise && <Lightbulb className="size-4 text-action-primary" aria-label="Includes exercise" />}{lesson.quiz && <HelpCircle className="size-4 text-action-primary" aria-label="Includes quiz" />}</summary><div className="border-t border-border-default p-4 sm:p-5"><p className="type-caption font-semibold tracking-wide text-action-primary uppercase">Learning objective</p><p className="mt-2 font-medium">{lesson.learningObjective}</p><p className="mt-5 leading-7 text-text-secondary">{lesson.summary}</p>{lesson.exercise && <div className="mt-5 rounded-md bg-blue-50 p-4"><p className="font-semibold">Exercise</p><p className="type-body-small mt-2 text-blue-900">{lesson.exercise.prompt}</p></div>}{lesson.quiz && <div className="mt-4 rounded-md border border-border-default p-4"><p className="font-semibold">Knowledge check</p><p className="mt-2">{lesson.quiz.question}</p><ul className="mt-3 grid gap-2">{lesson.quiz.options.map((option) => <li key={option.id} className="type-body-small rounded-sm bg-neutral-50 p-3 text-text-secondary">{option.id.toUpperCase()}. {option.text}</li>)}</ul></div>}</div></details>)}</div></div></details>)}</div></section>

        <section className="mt-10 grid gap-5 lg:grid-cols-2"><Card className="p-5 sm:p-6"><ClipboardCheck className="size-6 text-action-primary" aria-hidden="true" /><h2 className="type-title-large mt-4">{course.practicalTask.title}</h2><p className="type-body-small mt-2 leading-6 text-text-secondary">{course.practicalTask.instructions}</p><ul className="mt-4 grid gap-2">{course.practicalTask.deliverables.map((item) => <li key={item} className="type-body-small flex gap-2 text-text-secondary"><Check className="mt-0.5 size-4 text-status-success" aria-hidden="true" />{item}</li>)}</ul></Card><Card className="p-5 sm:p-6"><FileQuestion className="size-6 text-action-primary" aria-hidden="true" /><h2 className="type-title-large mt-4">{course.finalAssessment.title}</h2><p className="type-body-small mt-2 leading-6 text-text-secondary">{course.finalAssessment.instructions}</p><p className="type-body-small mt-4 font-semibold">Passing score: {course.finalAssessment.passingScore}%</p></Card></section>
        {course.certificateEnabled && <div className="mt-8 flex items-start gap-4 rounded-lg bg-yellow-50 p-5"><span className="flex size-10 shrink-0 items-center justify-center rounded-full bg-yellow-200 text-neutral-800"><Award className="size-5" aria-hidden="true" /></span><div><h2 className="font-semibold">Certificate available</h2><p className="type-body-small mt-1 text-neutral-700">Learners become eligible when they {course.completionCriteria === "all-lessons" ? "complete all lessons" : "pass the final assessment"}.</p></div></div>}
      </div>
    </article>
  );
}
